### ISSUE TITLE
Handling: Spawn Process terminated 

### ISSUE THREAD

**Issue by 89z** [httptoolkit/frida-android-unpinning#14]
If I use something like this:

~~~
frida --no-pause -U -l frida-script.js -W com.vimeo.android.videoapp
~~~

I get this result:

~~~
     ____
    / _  |   Frida 15.1.16 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to Android Emulator 5554 (id=emulator-5554)
Waiting for spawn to appear...
Handling: Spawn(pid=18656, identifier="com.vimeo.android.videoapp")
[Android Emulator 5554::re.compile('com.vimeo.android.videoapp') ]-> Process terminated
~~~

**Comment by pimterry** [comment]
Any kind of error in logcat?

If you try commenting out individual rules from the script, or even disabling everything inside the `Java.perform(...)` callback entirely, does that give any clues as to what causes this?

**Comment by pimterry** [comment]
> I dont know what logcat is

`adb logcat` will print Android's own logs from the connected device for the OS and all currently running applications. That will include lots of past logs, so I'd suggest running `adb logcat -T1` to start streaming logs without history, then reproduce the issue, then stop logging and look through the output for any errors.

> it seems same error result.

If emptying the script does nothing, then it's probably nothing to do with this script, and it's a general Frida issue. I'm not sure what could cause that, maybe they've implemented some kind of Frida detection, or maybe there's a Frida bug that's crashing their app? Hard to say. 

If you can reproduce this with an empty script using the latest Frida version, and there's no clues in the logs, then I would open a bug in the [Frida repo](https://github.com/frida/frida/) and see if they have any ideas what's going on here.

**Comment by 89z** [comment]
I got this:


~~~
02-10 12:08:45.793  7095  7717 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.vimeo.android.videoapp/.launch.LaunchActivity bnds=[23,1584][230,1794]} from uid 10022
02-10 12:08:45.801  7029  9221 W audio_hw_generic: Not supplying enough data to HAL, expected position 3242449 , only wrote 3242160
02-10 12:08:45.817 11980 11980 W zygote  : Unexpected CPU variant for X86 using defaults: x86
02-10 12:08:45.824  7095  7717 I ActivityManager: Start proc 11980:com.vimeo.android.videoapp/u0a77 for activity com.vimeo.android.videoapp/.launch.LaunchActivity
02-10 12:08:45.836  1444  1444 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
02-10 12:08:45.907  7786  7897 E ContentStoreEUAS: Failed to commit the deferred actions
02-10 12:08:49.012  7029  7029 W audio_hw_generic: Not supplying enough data to HAL, expected position 3548539 , only wrote 3396240
02-10 12:08:50.820  7732  7854 D EGL_emulation: eglMakeCurrent: 0x9b5a5220: ver 3 1 (tinfo 0x990ffb80)
02-10 12:08:50.820  7786  7982 D EGL_emulation: eglMakeCurrent: 0x9b885720: ver 3 1 (tinfo 0x9b883760)
02-10 12:08:52.042  7432  7489 I NetworkScheduler.Stats: Task com.google.android.gms/com.google.android.gms.auth.account.be.legacy.AuthCronService started execution. cause:4 exec_start_elapsed_seconds: 643 [CONTEXT service_id=218 ]
02-10 12:08:52.177  7432  7910 W Conscrypt: Could not set socket write timeout: java.net.SocketException: Socket closed
02-10 12:08:52.177  7432  7910 W Conscrypt:     at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@202414022@20.24.14 (040700-319035315):2)
02-10 12:08:52.177  7432  7910 W Conscrypt:     at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(:com.google.android.gms@202414022@20.24.14 (040700-319035315):0)
02-10 12:08:52.232  7432  7910 W Conscrypt: Could not set socket write timeout: java.net.SocketException: Socket closed
02-10 12:08:52.232  7432  7910 W Conscrypt:     at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@202414022@20.24.14 (040700-319035315):2)
02-10 12:08:52.232  7432  7910 W Conscrypt:     at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(:com.google.android.gms@202414022@20.24.14 (040700-319035315):0)
02-10 12:08:52.308  7432  7910 W GLSUser : [AppCertManager] IOException while requesting key:
02-10 12:08:52.308  7432  7910 W GLSUser : java.io.IOException: Invalid device key response.
02-10 12:08:52.308  7432  7910 W GLSUser :      at hwy.a(:com.google.android.gms@202414022@20.24.14 (040700-319035315):49)
02-10 12:08:52.308  7432  7910 W GLSUser :      at hww.a(:com.google.android.gms@202414022@20.24.14 (040700-319035315):45)
02-10 12:08:52.308  7432  7910 W GLSUser :      at hwr.a(:com.google.android.gms@202414022@20.24.14 (040700-319035315):0)
02-10 12:08:52.308  7432  7910 W GLSUser :      at hwu.a(:com.google.android.gms@202414022@20.24.14 (040700-319035315):10)
02-10 12:08:52.308  7432  7910 W GLSUser :      at gbi.call(:com.google.android.gms@202414022@20.24.14 (040700-319035315):0)
02-10 12:08:52.308  7432  7910 W GLSUser :      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-10 12:08:52.308  7432  7910 W GLSUser :      at soy.b(:com.google.android.gms@202414022@20.24.14 (040700-319035315):12)
02-10 12:08:52.308  7432  7910 W GLSUser :      at soy.run(:com.google.android.gms@202414022@20.24.14 (040700-319035315):7)
02-10 12:08:52.308  7432  7910 W GLSUser :      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
02-10 12:08:52.308  7432  7910 W GLSUser :      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
02-10 12:08:52.308  7432  7910 W GLSUser :      at sux.run(:com.google.android.gms@202414022@20.24.14 (040700-319035315):0)
02-10 12:08:52.308  7432  7910 W GLSUser :      at java.lang.Thread.run(Thread.java:764)
02-10 12:08:52.317  7432  7489 I NetworkScheduler.Stats: Task com.google.android.gms/com.google.android.gms.auth.account.be.legacy.AuthCronService finished executing. cause:4 result: 3 elapsed_millis: 285 uptime_millis: 285 exec_start_elapsed_seconds: 643 [CONTEXT service_id=218 ]
02-10 12:08:54.976  7095  7222 D WificondControl: Scan result ready event
02-10 12:08:55.799  7095  7110 W ActivityManager: Launch timeout has expired, giving up wake lock!
02-10 12:08:55.826  7095  7110 W ActivityManager: Process ProcessRecord{5836615 11980:com.vimeo.android.videoapp/u0a77} failed to attach
02-10 12:08:55.828  7095  7110 I ActivityManager: Killing 11980:com.vimeo.android.videoapp/u0a77 (adj -10000): start timeout
~~~

**Comment by 89z** [comment]
Using Frida `-f` or `-F` instead of `-W`, seems to work as expect. Although I dont think they really do the same thing, so I could be missing some requests when monitoring.

**Comment by pimterry** [comment]
> Using Frida -f or -F instead of -W, seems to work as expected. Although I don't think they really do the same thing, so I could be missing some requests when monitoring.

Ah, yes, that makes sense. Why were you using the `-W` argument? I didn't notice that, sorry, but yes that doesn't seem to be a documented argument of Frida at all anywhere I can see.

All my previous testing with Frida (e.g. https://httptoolkit.tech/blog/frida-certificate-pinning/) uses just `frida --no-pause -U -l <script> -f <package id>`, and I think that's normally what you want. Is there something specific that you were looking for using `-W`?

**Comment by pimterry** [comment]
> Just run frida -h

Turns out I'm still running Frida 14.2, and this is a new feature :smile:. Neat though, I can definitely see the use cases! Thanks for pointing that out, I'll look into it further.

Anyway, fair enough, glad you sorted this out anyway, even if it did mean writing a vimeo URL parser. Do let me know if you run into more issues like this, they're always interesting.

**Comment by 89z** [comment]
If youre interested, today I found a better way to do mobile deep linking:

https://github.com/89z/googleplay/blob/v1.8.8/docs/deep-linking.md
