### ISSUE TITLE
com.peacocktv.peacockandroid

### ISSUE THREAD

**Issue by 89z** [httptoolkit/frida-android-unpinning#29]
I start the app, then click Sign In. I enter Email and Password and click Sign In. Then I get:

> An error has occurred. Please try again.

I can share account for testing if need be.

**Comment by pimterry** [comment]
Ok, interesting, thanks for reporting that @89z. I'm afraid I don't have much time to look into this myself right now, sorry, but I'll see if I get some time later on or if anybody else here is keen to help out.

Do you have any clues to the underlying issue yet? Both the Frida script logs and your ADB logs from the device would be very useful, especially if there's any related errors listed in there. Or any clues you've found from unpackaging the app and tracing down the failure itself.

**Comment by pimterry** [comment]
> Ended up they use their own custom cert that is sent from client requests for certain domains. If the cert isn't there, you get error. This is why the proxied requests would fail.

This makes sense, and I think if they're doing that level of auth it's not uncommon that they'll do checks for emulators etc with SafetyNet or similar and block execution in those environments, which would explain your other issue.

For client certs like these, for any intercepting proxy, you'll need to extract the cert and configure the proxy to use it for upstream connections. For HTTP Toolkit, you can add it on the settings page and configure which hostnames it should be used for there.

**Comment by yoshimo** [comment]
you can try https://github.com/rednaga/APKiD to test the apk for a few possible checks
Root-Check detection is yet to be done.

**Comment by 89z** [comment]
> you can try https://github.com/rednaga/APKiD to test the apk for a few possible checks Root-Check detection is yet to be done.

Hm interesting - I will see if I can try that one. Root-Check might actually be the problem - since my physical phone is not rooted, but the emulator is rooted. Also I can try a non-rooted emulator, so see if that changes anything. Thanks!

**Comment by pimterry** [comment]
> Do either of you have experience rooting a physical device?

Yep, I almost always use rooted physical devices for testing, there's quite a few apps that will refuse to work on emulators.

**Comment by 89z** [comment]
Do I need some special software? or can you point me to something to get me started?

**Comment by pimterry** [comment]
You want to buy a phone that you're happy to wipe and potentially brick, for starters (I'd suggest getting something 2nd hand that was popular a couple of years ago).

The specific steps involved vary significantly depending on the device. I would search for docs for devices you're looking at purchasing (before you purchase - there's a few rare models that are not rootable at all).

In general, you usually need to:

* Flash a recovery image (this lets you hold a special key during boot to get into recovery mode, to flash a full OS) like [TWRP](https://twrp.me/about/)
* Use the recovery image to flash a custom OS like [LineageOS](https://lineageos.org/)
* Install [Magisk](https://themagisk.com/) and enable root

It's hard to be more specific though, the process changes frequently with new releases of both Android itself and all the rooting/custom ROM projects & tools, and the steps always vary by device too.

Buy something reasonably popular and there'll be 1000 more specific step-by-step guides on google.

**Comment by 89z** [comment]
> Both the Frida script logs

Seems normal, could just be that the script needs to add some additional bypass:

~~~
     ____
    / _  |   Frida 16.0.2 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to Android Emulator 5554 (id=emulator-5554)
Spawned `com.peacocktv.peacockandroid`. Resuming main thread!
[Android Emulator 5554::com.peacocktv.peacockandroid ]-> ---
Unpinning Android app...
[+] SSLPeerUnverifiedException auto-patcher
[+] HttpsURLConnection (setDefaultHostnameVerifier)
[+] HttpsURLConnection (setSSLSocketFactory)
[+] HttpsURLConnection (setHostnameVerifier)
[+] SSLContext
[ ] TrustManagerImpl
[+] OkHTTPv3 (list)
[ ] OkHTTPv3 (cert)
[+] OkHTTPv3 (cert array)
[+] OkHTTPv3 ($okhttp)
[ ] Trustkit OkHostnameVerifier(SSLSession)
[ ] Trustkit OkHostnameVerifier(cert)
[ ] Trustkit PinningTrustManager
[ ] Appcelerator PinningTrustManager
[+] OpenSSLSocketImpl Conscrypt
[ ] OpenSSLEngineSocketImpl Conscrypt
[ ] OpenSSLSocketImpl Apache Harmony
[ ] PhoneGap sslCertificateChecker
[ ] IBM MobileFirst pinTrustedCertificatePublicKey (string)
[ ] IBM MobileFirst pinTrustedCertificatePublicKey (string array)
[ ] IBM WorkLight HostNameVerifierWithCertificatePinning (SSLSocket)
[ ] IBM WorkLight HostNameVerifierWithCertificatePinning (cert)
[ ] IBM WorkLight HostNameVerifierWithCertificatePinning (string string)
[ ] IBM WorkLight HostNameVerifierWithCertificatePinning (SSLSession)
[+] Conscrypt CertPinManager
[ ] CWAC-Netsecurity CertPinManager
[ ] Worklight Androidgap WLCertificatePinningPlugin
[ ] Netty FingerprintTrustManagerFactory
[ ] Squareup CertificatePinner (cert)
[ ] Squareup CertificatePinner (list)
[ ] Squareup OkHostnameVerifier (cert)
[ ] Squareup OkHostnameVerifier (SSLSession)
[+] Android WebViewClient (SslErrorHandler)
[ ] Android WebViewClient (WebResourceError)
[ ] Apache Cordova WebViewClient
[ ] Boye AbstractVerifier
[ ] Appmattus (Transparency)
Unpinning setup completed
---
  --> Bypassing OpenSSLSocketImpl Conscrypt
  --> Bypassing Trustmanager (Android < 7) request
  --> Bypassing Trustmanager (Android < 7) request
  --> Bypassing Trustmanager (Android < 7) request
  --> Bypassing OpenSSLSocketImpl Conscrypt
  --> Bypassing OpenSSLSocketImpl Conscrypt
  --> Bypassing OpenSSLSocketImpl Conscrypt
  --> Bypassing Trustmanager (Android < 7) request
  --> Bypassing OpenSSLSocketImpl Conscrypt
  --> Bypassing Trustmanager (Android < 7) request
  --> Bypassing Trustmanager (Android < 7) request
  --> Bypassing OpenSSLSocketImpl Conscrypt
  --> Bypassing OpenSSLSocketImpl Conscrypt
  --> Bypassing OpenSSLSocketImpl Conscrypt
  --> Bypassing OpenSSLSocketImpl Conscrypt
  --> Bypassing OkHTTPv3 ($okhttp): www.peacocktv.com
  --> Bypassing Conscrypt CertPinManager: www.peacocktv.com
  --> Bypassing OpenSSLSocketImpl Conscrypt
  --> Bypassing OkHTTPv3 ($okhttp): config.clients.peacocktv.com
  --> Bypassing OpenSSLSocketImpl Conscrypt
  --> Bypassing OkHTTPv3 ($okhttp): init.clients.peacocktv.com
  --> Bypassing OpenSSLSocketImpl Conscrypt
  --> Bypassing OkHTTPv3 ($okhttp): atom.peacocktv.com
  --> Bypassing OpenSSLSocketImpl Conscrypt
  --> Bypassing OkHTTPv3 ($okhttp): meg.disco.peacocktv.com
  --> Bypassing OpenSSLSocketImpl Conscrypt
  --> Bypassing Trustmanager (Android < 7) request
  --> Bypassing Trustmanager (Android < 7) request
  --> Bypassing Trustmanager (Android < 7) request
  --> Bypassing Trustmanager (Android < 7) request
  --> Bypassing OpenSSLSocketImpl Conscrypt
  --> Bypassing OkHTTPv3 ($okhttp): mobile-data.onetrust.io
  --> Bypassing OpenSSLSocketImpl Conscrypt
  --> Bypassing OkHTTPv3 ($okhttp): init.clients.peacocktv.com
  --> Bypassing Trustmanager (Android < 7) request
  --> Bypassing Trustmanager (Android < 7) request
  --> Bypassing Trustmanager (Android < 7) request
  --> Bypassing Trustmanager (Android < 7) request
  --> Bypassing Trustmanager (Android < 7) request
  --> Bypassing OpenSSLSocketImpl Conscrypt
  --> Bypassing OkHTTPv3 ($okhttp): imageservice.disco.peacocktv.com
  --> Bypassing Conscrypt CertPinManager: imageservice.disco.peacocktv.com
  --> Bypassing Conscrypt CertPinManager: atom.peacocktv.com
  --> Bypassing OkHTTPv3 (list): rango.id.peacocktv.com
  --> Bypassing Trustmanager (Android < 7) request
  --> Bypassing Trustmanager (Android < 7) request
  --> Bypassing OkHTTPv3 (list): rango.id.peacocktv.com
  --> Bypassing OpenSSLSocketImpl Conscrypt
  --> Bypassing OpenSSLSocketImpl Conscrypt
  --> Bypassing OkHTTPv3 ($okhttp): g005-sf-us-cmaf-prd-ak.cdn.peacocktv.com
  --> Bypassing OpenSSLSocketImpl Conscrypt
  --> Bypassing OpenSSLSocketImpl Conscrypt
  --> Bypassing OkHTTPv3 ($okhttp): g005-sf-us-cmaf-prd-ak-a280.cdn.peacocktv.com
  --> Bypassing OkHTTPv3 ($okhttp): g005-sf-us-cmaf-prd-ak-a280.cdn.peacocktv.com
  --> Bypassing Trustmanager (Android < 7) request
  --> Bypassing Trustmanager (Android < 7) request
  --> Bypassing OpenSSLSocketImpl Conscrypt
  --> Bypassing OpenSSLSocketImpl Conscrypt
  --> Bypassing OpenSSLSocketImpl Conscrypt
  --> Bypassing OkHTTPv3 ($okhttp): rango.id.peacocktv.com
  --> Bypassing OkHTTPv3 ($okhttp): www.peacocktv.com
  --> Bypassing Trustmanager (Android < 7) request
  --> Bypassing Conscrypt CertPinManager: www.peacocktv.com
~~~

> and your ADB logs from the device

Do get an exception here:

~~~
10-22 09:36:15.955  2792  3760 W GLSUser : [AppCertManager] IOException while requesting key:
10-22 09:36:15.955  2792  3760 W GLSUser : java.io.IOException: Invalid device key response.
10-22 09:36:15.955  2792  3760 W GLSUser :      at hwy.a(:com.google.android.gms@202414022@20.24.14 (040700-319035315):49)
10-22 09:36:15.955  2792  3760 W GLSUser :      at hww.a(:com.google.android.gms@202414022@20.24.14 (040700-319035315):45)
10-22 09:36:15.955  2792  3760 W GLSUser :      at hwr.a(:com.google.android.gms@202414022@20.24.14 (040700-319035315))
10-22 09:36:15.955  2792  3760 W GLSUser :      at hwu.a(:com.google.android.gms@202414022@20.24.14 (040700-319035315):10)
10-22 09:36:15.955  2792  3760 W GLSUser :      at gbi.call(:com.google.android.gms@202414022@20.24.14 (040700-319035315):0)
10-22 09:36:15.955  2792  3760 W GLSUser :      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-22 09:36:15.955  2792  3760 W GLSUser :      at soy.b(:com.google.android.gms@202414022@20.24.14 (040700-319035315):12)
10-22 09:36:15.955  2792  3760 W GLSUser :      at soy.run(:com.google.android.gms@202414022@20.24.14 (040700-319035315):7)
10-22 09:36:15.955  2792  3760 W GLSUser :      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-22 09:36:15.955  2792  3760 W GLSUser :      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-22 09:36:15.955  2792  3760 W GLSUser :      at sux.run(:com.google.android.gms@202414022@20.24.14 (040700-319035315):0)
10-22 09:36:15.955  2792  3760 W GLSUser :      at java.lang.Thread.run(Thread.java:818)
~~~

Note I also tried a non-rooted Virtual Device, to see what would happen. However the error remains, so it could just be the app is checking for Virtual Device, regardless if its rooted or not.

**Comment by 89z** [comment]
> you can try https://github.com/rednaga/APKiD to test the apk

~~~
[+] APKiD 2.1.4 :: from RedNaga :: rednaga.io
[*] .\com.peacocktv.peacockandroid-121031024.apk!classes.dex
 |-> anti_vm : Build.FINGERPRINT check, Build.MANUFACTURER check, Build.TAGS check, network operator name check
 |-> compiler : r8
 |-> obfuscator : unreadable field names, unreadable method names
[*] .\com.peacocktv.peacockandroid-121031024.apk!classes2.dex
 |-> compiler : r8 without marker (suspicious)
[*] .\com.peacocktv.peacockandroid-121031024.apk!classes3.dex
 |-> anti_vm : Build.BOARD check, Build.FINGERPRINT check, Build.MANUFACTURER check, Build.MODEL check, Build.PRODUCT check, Build.TAGS check, network operator name check, possible Build.SERIAL check
 |-> compiler : r8 without marker (suspicious)
[*] .\com.peacocktv.peacockandroid-121031024.apk!classes4.dex
 |-> anti_vm : Build.BOARD check, Build.FINGERPRINT check, Build.MANUFACTURER check, possible Build.SERIAL check
 |-> compiler : r8 without marker (suspicious)
 |-> obfuscator : unreadable field names, unreadable method names
[*] .\com.peacocktv.peacockandroid-121031024.apk!classes5.dex
 |-> anti_vm : Build.FINGERPRINT check, Build.MANUFACTURER check, network operator name check
 |-> compiler : r8 without marker (suspicious)
[*] .\com.peacocktv.peacockandroid-121031024.apk!classes6.dex
 |-> anti_vm : Build.FINGERPRINT check, Build.MANUFACTURER check, Build.MODEL check, Build.PRODUCT check, Build.TAGS check, SIM operator check, possible Build.SERIAL check
 |-> compiler : r8 without marker (suspicious)
~~~

**Comment by 89z** [comment]
OK I was finally able to get past the login using Android Studio. All my tests until now, I was trying without MITM. I figured I just wanted to try it "normally" first without trying to capture anything. Since that wasn't working, I decided to try MITM just for the hell of it. So I installed system certificate, no Frida (AKA easy mode). Sure enough, I was able to intercept all requests up to and including the failed login request:

~~~
POST https://rango.id.peacocktv.com/signin/service/international HTTP/2.0
content-type: application/x-www-form-urlencoded
x-skyott-device: MOBILE
x-skyott-proposition: NBCUOTT
x-skyott-provider: NBCU
x-skyott-territory: US

userIdentifier=MY_EMAIL&password=MY_PASSWORD
~~~

However on the response for that one, I noticed something strange:

~~~
429 Too Many Requests
~~~

I played with the request, and for some reason this header is what fucks it up:

~~~
x-skyott-device: MOBILE
~~~

If you use your MITM tool to remove this header, then the request works, and you make it to the next screen. However couple more snags. If you start MITM before the app, you can capture everything up to and including the login, but it fails after that, even with the workaround above. So you probably want to MITM once to capture the initial requests, then kill the app and run again, but don't start the MITM this time until AFTER the app starts. This will allow you (along with the header trick) to get past the login (with valid credentials of course).

**Comment by 89z** [comment]
gonna close this for now. I haven't fully tested the app, so Frida might still be needed for something, so I can reopen later if need be. Thanks everyone for the responses!
